services:
  frontend:
    image: naser03/cicddevopsproject-frontend:latest
    container_name: taskmanager-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    image: naser03/cicddevopsproject-backend:latest
    container_name: taskmanager-backend
    expose:
      - "5000"
    restart: unless-stopped